from __future__ import annotations
from enum import IntEnum, Enum

class RiskClass(str, Enum):
    LOW='LOW'; MODERATE='MODERATE'; HIGH='HIGH'; VERY_HIGH='VERY_HIGH'; CRITICAL='CRITICAL'
class ScaleClass(IntEnum):
    S0_TOY=0; S1_SMALL=1; S2_WORKSTATION=2; S3_MULTICORE_WORKSTATION=3; S4_SINGLE_NODE_HPC=4; S5_MULTI_NODE_HPC=5; S6_LARGE_DISTRIBUTED=6; S7_EXTREME_DISTRIBUTED=7
class QualificationLevel(IntEnum):
    Q0_UNKNOWN=0; Q1_AVAILABLE=1; Q2_TESTED=2; Q3_BENCHMARKED=3; Q4_INDUSTRIALLY_VALIDATED=4; Q5_CERTIFICATION_ACCEPTABLE=5
class MaturityLevel(IntEnum):
    M0_CONCEPT=0; M1_IMPLEMENTED=1; M2_UNIT_TESTED=2; M3_NUMERICALLY_VERIFIED=3; M4_BENCHMARKED=4; M5_STRESS_TESTED=5; M6_EXTERNALLY_REPRODUCED=6; M7_INDUSTRIALLY_VALIDATED=7; M8_QUALIFIED_DEFINED_CONTEXT=8
class ConfidenceClass(IntEnum):
    C0_UNASSESSED=0; C1_EXPLORATORY=1; C2_VERIFIED=2; C3_VALIDATED=3; C4_MULTI_SOLVER_CONFIRMED=4; C5_EXTERNALLY_REPRODUCED=5; C6_QUALIFIED_DEFINED_CONTEXT=6
class ReproducibilityClass(IntEnum):
    R0_NOT_REPRODUCIBLE=0; R1_LOCALLY_REPEATABLE=1; R2_CLEAN_ENV_REPEATABLE=2; R3_CROSS_MACHINE=3; R4_CROSS_IMPLEMENTATION=4; R5_INDEPENDENTLY_REPRODUCED=5
class WorkflowMode(str, Enum):
    RESEARCH='RESEARCH'; PRODUCTION='PRODUCTION'; CERTIFICATION_SUPPORT='CERTIFICATION_SUPPORT'
class ClaimLevel(IntEnum):
    IMPLEMENTED=1; TESTED=2; NUMERICALLY_VERIFIED=3; VALIDATED=4; BENCHMARKED=5; STRESS_TESTED=6; ENDURANCE_TESTED=7; EXTERNALLY_REPRODUCED=8; INDUSTRIALLY_VALIDATED=9; CERTIFICATION_ACCEPTABLE=10
class FailureCode(str, Enum):
    INVALID_INPUT='INVALID_INPUT'; MODEL_OUT_OF_DOMAIN='MODEL_OUT_OF_DOMAIN'; MESH_FAILURE='MESH_FAILURE'; NONCONVERGED='NONCONVERGED'; NUMERICAL_BREAKDOWN='NUMERICAL_BREAKDOWN'; RESOURCE_EXHAUSTION='RESOURCE_EXHAUSTION'; BACKEND_UNAVAILABLE='BACKEND_UNAVAILABLE'; TOOL_EXECUTION_FAILURE='TOOL_EXECUTION_FAILURE'; QUALIFICATION_INSUFFICIENT='QUALIFICATION_INSUFFICIENT'; VALIDATION_FAILURE='VALIDATION_FAILURE'; DISCREPANCY_FAILURE='DISCREPANCY_FAILURE'; REPRODUCIBILITY_FAILURE='REPRODUCIBILITY_FAILURE'
